# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Future Imperfect"
license = "MIT"
licenselink = "https://github.com/rowing-matters/hugo-future-imperfect/blob/master/LICENSE.md"
description = "Customized fork of jpescador/hugo-future-imperfect. "
homepage = "https://github.com/rowing-matters/hugo-future-imperfect"
tags = ["blog", "responsive", "font awesome", "highlight.js", "fancybox 3", "staticman", "netlify"]
features = ["html5", "css3", "responsive"]
min_version = 0.51

[author]
  name = "Rowing Matters"
  homepage = "https://rowing-matters.de/"

# If porting an existing theme
[original]
  name = "Hugo Future Imperfect"
  homepage = "https://github.com/jpescador/hugo-future-imperfect"
  repo = "https://github.com/jpescador/hugo-future-imperfect.git"
